# Generated by Django 3.2.5 on 2021-07-26 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_list_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.RunSQL("INSERT INTO polls_questionlist (question_list_text) VALUES ('Suffer');"),
        migrations.AddField(
            model_name='question',
            name='question_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.questionlist'),
            preserve_default=False,
        ),
    ]
