# Generated by Django 3.2.5 on 2021-07-27 05:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_question_list_question_questionlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionlist',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
