# Generated by Django 3.2.5 on 2021-07-28 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_questionlist_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=200)),
                ('date_start', models.TimeField()),
                ('date_end', models.TimeField(default=0)),
                ('questionlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.questionlist')),
            ],
        ),
        migrations.CreateModel(
            name='ResultChoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_id', models.IntegerField(default=0)),
                ('question_id', models.IntegerField(default=0)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.resultsmodel')),
            ],
        ),
    ]
