# Generated by Django 3.2.5 on 2021-07-28 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_resultchoicemodel_resultsmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultsmodel',
            name='uid',
        ),
    ]
