# Generated by Django 3.2.5 on 2021-07-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_resultsmodel_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultsmodel',
            name='uid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
