# Generated by Django 3.2.5 on 2021-07-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_resultsmodel_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultsmodel',
            name='date_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='resultsmodel',
            name='date_start',
            field=models.DateTimeField(),
        ),
    ]
