# Generated by Django 3.2.5 on 2021-07-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20210728_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultsmodel',
            name='date_end',
            field=models.DateTimeField(blank=True),
        ),
    ]
