# Generated by Django 3.2.5 on 2021-07-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_resultsmodel_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultsmodel',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
