# Generated by Django 3.2.5 on 2021-07-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_alter_resultsmodel_date_end'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='resultchoicemodel',
            constraint=models.UniqueConstraint(fields=('question_id', 'result_id'), name='unique_choice'),
        ),
    ]
